---
#
# Ansible managed
#
repository:
  description: Configure sysctl settings
  homepage: https://mullholland.net
  topics: cloud, development, networking, packaging, system, ansible, molecule, tox, playbook
